name: build-and-deploy

on:
  push:
#    branches:
#      - environment/**
#      - '!environment/prod-**'
    # Sequence of patterns matched against refs/tags
    tags:
      - 2
      - 1.*

jobs:
  check_environment:
    runs-on: macos-10.15
    steps:
    - name: Check for valid env
#      if: startsWith(github.ref, 'refs/heads/environment/')
      run: |
        echo "ENVIRONMENT=true" >> $GITHUB_ENV
    - name: Fail job if not in the right branch
      if: ${{ env.ENVIRONMENT == '' }}
      run: |
        echo "Wrong environment name set"
        exit 1
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set env
      run: | 
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Update the version
      run: |
        sed -i .bak "s/MARKETING_VERSION[ ].*/MARKETING_VERSION = $ENVV;/g" ios/SchoolyMobile.xcodeproj/project.pbxproj
    - name: Read project.pbxproj
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: ios/SchoolyMobile.xcodeproj/project.pbxproj
    - name: Echo project.pbxproj
      run: echo "${{ steps.package.outputs.content }}"
