name: build-and-deploy

on:
  push:
    branches:
      - master
      - develop
      - environment/**
      - '!environment/prod-**'
  workflow_dispatch:
    inputs:
      maintenanceMode:
        description: "Maintenance Mode"
        required: true
        default: 'false'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nelonoel/branch-name@v1.0.1
    # Use branch name for whatever purpose
    - run: |
        echo ${BRANCH_NAME}
        sleep 100
