name: build-and-deploy

on:
  push:
    branches:
      - develop2
      - environment/**
      - '!environment/prod-**'
  workflow_dispatch:
    inputs:
      maintenanceMode:
        description: "Maintenance Mode"
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - name: Running on the default branch.
        if: steps.branch-name.outputs.is_default == 'true'
        run: |
          echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set environment variable and current repository
        run: |
          if [[ ${{ steps.branch-name.outputs.current_branch }} == "develop2" ]]; then
            ENVIRONMENT=dev-treehive
          else
            ENVIRONMENT=$(echo ${{ steps.branch-name.outputs.current_branch }} |  awk -F '/' '{print $NF}')
          fi
          echo $ENVIRONMENT >> test_file
